name: Setup Swift Test
on:
  push:
    branches:
      - main
jobs:
  setup-swift:
    strategy:
        matrix:
            os: [ubuntu-24.04, ubuntu-22.04, macos-14, macos-15]
            swift-version: ['6.1.0', '6.1.1', '6.1.5']
            soft-fail-version-check: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Swift
        uses: sonderformat-llc/setup-swift@main
        with:
          swift-version: ${{ matrix.swift-version }}
          soft-fail-version-check: ${{ matrix.soft-fail-version-check }}

      - name: Verify Swift version
        run: swift --version
